#!/bin/bash
echo "Setting hostname: "
curl -X PATCH --header "Content-Type:application/json" \
    --data '{"network": {"hostname": "balenaSound"}}' \
    "$BALENA_SUPERVISOR_ADDRESS/v1/device/host-config?apikey=$BALENA_SUPERVISOR_API_KEY"

echo -e "\n"
python /usr/src/app/bt-speaker/bt_speaker.py
