FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

ARG SNAPCAST_VERSION=0.17.1

WORKDIR /usr/src

RUN install_packages wget libavahi-client3 libavahi-common3 libflac8 libogg0 libopus0 libvorbis0a libvorbisenc2
RUN wget 'https://github.com/badaix/snapcast/releases/download/v'$SNAPCAST_VERSION'/snapserver_'$SNAPCAST_VERSION'-1_armhf.deb'
RUN dpkg -i 'snapserver_'$SNAPCAST_VERSION'-1_armhf.deb'

COPY snapserver.conf /etc/snapserver.conf

CMD [ "snapserver" ]